sudo: required
services:
  - docker

env:
  global:
    #
    - SHA=$(git rev-parse HEAD)
    # disables prompts from google cloud
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # decrypt service-account.json (created by google cloud and encrypted by travis)
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account/gc-service-account.json.enc -out gc-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # run script in service-account.json
  - gcloud auth activate-service-account --key-file service-account.json
  # link to project id from google cloud nav bar
  - gcloud config set project vidly-255215
  # link to from google cloud kubernetes engine/cluster Ort
  - gcloud config set compute/zone europe-west1-b
  # link to from google cloud kubernetes engine/cluster name
  - gcloud container clusters get-credentials vildy-cluster
  #  DOCKER_PASSWORD and DOCKER_USERNAME set in travis env variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker build-t arwedstorm/vidly	.

# script:
#    - docker run arwedstorm/vidly
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
