apiVersion: skaffold/v1beta16
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: arwedstorm/vidly
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: "app/"
        # "**/*.css": .
        # "**/*.html": .
deploy:
  kubectl:
    manifests:
      - k8s/vidly-deployment.yaml
      - k8s/vidly-cluster-ip-service.yaml
