apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    # removes path appendix (/api):
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # 
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'


spec:
  tls:
    - hosts:
        - sabbas.com
        - www.sabbas.com
      secretName: sabbas-com

  rules:
    - host: sabbas.com 
      http:
        paths:
          - path: /
            backend:
              serviceName: vidly-cluster-ip-service
              servicePort: 3000
          #  - path: /?(.*)
          #    backend:
          #      serviceName: vidly-cli-cluster-ip-service
          #      servicePort: 3000
              - host: sabbas.com 
    - host: www.sabbas.com  
      http:
        paths:
          - path: /
            backend:
              serviceName: vidly-cluster-ip-service
              servicePort: 3000
          #  - path: /?(.*)
          #    backend:
          #      serviceName: vidly-cli-cluster-ip-service
          #      servicePort: 3000
