apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    # removes path appendix (/api):
    # nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: vidly-cluster-ip-service
              servicePort: 3000
          #  - path: /?(.*)
          #    backend:
          #      serviceName: vidly-cli-cluster-ip-service
          #      servicePort: 3000
