apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata: name letsencrypt-prod
spec:
  acme:
    server: https://acme-02.api.letsencrypt.org/directory
    email: "heike.storm@web.de"
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
