apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: sabbas-de
  namespace: cert-manager-test
spec:
  acme:
    email: heike.storm@web.de
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
# apiVersion: cert-manager.io/v1alpha2
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-prod
# spec:
#   acme:
#     # You must replace this email address with your own.
#     # Let's Encrypt will use this to contact you about expiring
#     # certificates, and issues related to your account.
#     email: heike.storm@web.de
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       # Secret resource used to store the account's private key.
#       name: letsencrypt-prod
#     # Add a single challenge solver, HTTP01 using nginx
#     solvers:
#       - http01:
#           ingress:
#             class: nginx

# apiVersion: certmanager.k8s.io/v1alpha1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-prod
# spec:
#   acme:
#     server: https://acme-02.api.letsencrypt.org/directory
#     email: "heike.storm@web.de"
#     privateKeySecretRef:
#       name: letsencrypt-prod
#     http01: {}
