apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidly-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: vidly

  template:
    metadata:
      labels:
        component: vidly
    spec:
      containers:
        - name: vidly
          image: arwedstorm/vidly
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: pg-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
